### ISSUE TITLE
Does the web interface work?

### ISSUE THREAD

**Issue by aykaramba** [tamurashingo/reddit1.0#11]
Hi.

Thanks for updating the Reddit software!  

I have setup a db, migrated the db data and started up the server.  When I go to http://localhost:8000 I see the Hunchentoot welcome screen, not a Reddit page.  I don't see anything in main.lisp that refers to what should render in /.  In addition, /help, /blog and all of the other routes provide an Internal Server Error.  For example:

127.0.0.1 - [2023-07-30 02:36:53] "GET /help/help.html HTTP/1.1" 500 293 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 uacq"
[2023-07-30 02:37:24 [ERROR]] Condition CL-MEMCACHED::MEMCACHED-SERVER-UNREACHABLE was signalled.
Backtrace for: #<SB-THREAD:THREAD "hunchentoot-worker-127.0.0.1:48504" RUNNING {10068E9253}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {7F9050EFDE63}>)
1: (HUNCHENTOOT::GET-BACKTRACE)
2: ((FLET "H0" :IN HUNCHENTOOT:HANDLE-REQUEST) #<CL-MEMCACHED::MEMCACHED-SERVER-UNREACHABLE {100693DD53}>)
3: (SB-KERNEL::%SIGNAL #<CL-MEMCACHED::MEMCACHED-SERVER-UNREACHABLE {100693DD53}>)
4: (ERROR CL-MEMCACHED::MEMCACHED-SERVER-UNREACHABLE)
5: (CL-MEMCACHED::NEW-MEMCACHE-CONNECTION #<MEMCACHED-SERVER Name:reddit memcached IP:127.0.0.1 Port:11211 >)
6: (CL-MEMCACHED:MC-GET ("PAGE-FRONT-NIL") :MEMCACHE #<MEMCACHED-SERVER Name:reddit memcached IP:127.0.0.1 Port:11211 > :MC-USE-POOL NIL)
7: (CL-MEMCACHED:MC-GET+ "PAGE-FRONT-NIL" :MEMCACHE #<MEMCACHED-SERVER Name:reddit memcached IP:127.0.0.1 Port:11211 > :MC-USE-POOL NIL)
8: (CL-MEMCACHED:MC-GET-VALUE "PAGE-FRONT-NIL" :MEMCACHE #<MEMCACHED-SERVER Name:reddit memcached IP:127.0.0.1 Port:11211 > :MC-USE-POOL NIL :EXTERNAL-FORMAT NIL)
9: (REDDIT.WEB::PAGE-FRONT)
10: ((:METHOD HUNCHENTOOT:HANDLE-REQUEST (HUNCHENTOOT:ACCEPTOR HUNCHENTOOT:REQUEST)) #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 8000)> #<HUNCHENTOOT:REQUEST {100693B873}>) [fast-method]
11: ((:METHOD HUNCHENTOOT:PROCESS-REQUEST (T)) #<HUNCHENTOOT:REQUEST {100693B873}>) [fast-method]
12: (HUNCHENTOOT::DO-WITH-ACCEPTOR-REQUEST-COUNT-INCREMENTED #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 8000)> #<FUNCTION (LAMBDA NIL :IN HUNCHENTOOT:PROCESS-CONNECTION) {100693B73B}>)
13: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION (HUNCHENTOOT:ACCEPTOR T)) #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 8000)> #<USOCKET:STREAM-USOCKET {10068E8CB3}>) [fast-method]
14: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENTOOT:ACCEPTOR T)) #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 8000)> #<USOCKET:STREAM-USOCKET {10068E8CB3}>) [fast-method]
15: ((:METHOD HUNCHENTOOT::HANDLE-INCOMING-CONNECTION% (HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER T)) #<HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER {1006CA0133}> #<USOCKET:STREAM-USOCKET {10068E8CB3}>) [fast-method]
16: ((LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
17: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
19: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
20: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
21: (SB-THREAD::RUN)
22: ("foreign function: call_into_lisp_")
23: ("foreign function: funcall1")

127.0.0.1 - [2023-07-30 02:37:24] "GET /help/help.html HTTP/1.1" 500 293 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 uacq"
CL-USER> 

I don't see anything in the error message that tells me what might be going on.

Anyway, this isn't an issue, I just wanted to find out what is expected behaviour and what we need to know.

Thanks.

**Comment by tamurashingo** [comment]
This is happening because memcached is not running. It is a bug.
I will add a configuration to docker-compose to start memcached.

Thanks!
